# Calcul Numeric - Subiecte de examen

In [30]:
import math
import numpy as np
import matplotlib.pyplot as plt

## Exercițiul 1

Metoda bisecției - secțiunea I.1 din [cursul 1](https://drive.google.com/file/d/1hUFKessAxlGIT_gNFlH7-4yyuyQ_4vFe/view)

### a)

Pentru a găsi intervalele de monotonie ale lui $f(x) = x^3 - 4x + 1$, calculăm derivata funcției: $f'(x) = 3x^2 - 4$.

Vedem că derivata se anulează în $\pm \frac{2 \sqrt{3}}{3}$. Deci intervalele de monotonie sunt:
- $\left(-\infty, -\frac{2 \sqrt{3}}{3}\right)$
- $\left(-\frac{2 \sqrt{3}}{3}, +\frac{2 \sqrt{3}}{3}\right)$
- $\left(+\frac{2 \sqrt{3}}{3}, +\infty\right)$

### b)

Observăm că $f\left(+ \frac{2 \sqrt{3}}{3}\right) < 0$, și de exemplu $f(4) > 0$. Deci în acest interval funcția are cel puțin o soluție reală. Dar deoarece este și monotonă pe $\left(\frac{2 \sqrt{3}}{3}, +\infty\right)$, această soluție este unică.

### c)

In [31]:
def bisection_search(f, a, b, epsilon=1e-3):
    # Calculăm valorile în capete
    f_a = f(a)
    f_b = f(b)

    # Prima estimare, mijlocul intervalului inițial
    x_num = (a + b) / 2

    # Numărul necesar de iterații
    num_iterations = math.floor(math.log2((b - a) / epsilon) - 1) + 1
    
    last_rel_error = math.inf

    # Aplicăm algoritmul
    for step in range(num_iterations):
    
        print(f"a = {a}, b = {b}, error = {last_rel_error}")
        value = f(x_num)

        # Am găsit fix valoarea căutată, ieșim
        if value == 0:
            break
        elif f_a * value < 0:
            b = x_num
        else:
            a = x_num
        
        x_num_vechi = x_num
        x_num = (a + b) / 2
        
        last_rel_error = abs((x_num - x_num_vechi)) / abs(x_num_vechi + epsilon)

    return x_num

f = lambda x: x ** 3 - 4 * x + 1
print("x1 =", bisection_search(f, -4, -1))
print("x2 =", bisection_search(f, -1, 1))
print("x3 =", bisection_search(f, 1, 4))

a = -4, b = -1, error = inf
a = -2.5, b = -1, error = 0.30012004801920766
a = -2.5, b = -1.75, error = 0.2144082332761578
a = -2.125, b = -1.75, error = 0.08827683615819208
a = -2.125, b = -1.9375, error = 0.04841208365608055
a = -2.125, b = -2.03125, error = 0.023088289619504987
a = -2.125, b = -2.078125, error = 0.011283625203105253
a = -2.125, b = -2.1015625, error = 0.005578862804605909
a = -2.125, b = -2.11328125, error = 0.0027739558830056367
a = -2.119140625, b = -2.11328125, error = 0.0013831411689202646
a = -2.1162109375, b = -2.11328125, error = 0.0006925284490686877
x1 = -2.115478515625
a = -1, b = 1, error = inf
a = 0.0, b = 1, error = 500.0
a = 0.0, b = 0.5, error = 0.499001996007984
a = 0.25, b = 0.5, error = 0.49800796812749004
a = 0.25, b = 0.375, error = 0.16622340425531915
a = 0.25, b = 0.3125, error = 0.09968102073365231
a = 0.25, b = 0.28125, error = 0.05535872453498671
a = 0.25, b = 0.265625, error = 0.029301453352086265
a = 0.25, b = 0.2578125, error = 0.015092972

## Exercițiul 2

Metoda Newton-Rhapson - secțiunea I.2 din [cursul 1](https://drive.google.com/file/d/1hUFKessAxlGIT_gNFlH7-4yyuyQ_4vFe/view)

### a)

#### Formula

Formula pentru următorul din șirul aproximărilor este

$$x_k = x_{k-1} - \frac{f (x_{k-1})}{f'(x_{k - 1})}$$

#### Convergență 

Fie $f \in C^2([a, b])$, $f'$ și $f''$ nu se anulează pe $[a, b]$ și $f(a) f(b) < 0$. 

Fie $x_0 \in [a, b]$ astfel încât să aibă loc condiția

$$f(x_0) f''(x_0) > 0$$

atunci ecuația $f(x) = 0$ are o soluție unică $x^* \in (a, b)$ iar șirul $x_k$ construit prin metoda Newton-Rhapson converge la $x^*$.

### b)

Fie $f(x) = x^2 + 2 x − 1$, $f \colon [0.1, 2] \to \mathbb{R}$.

Atunci $f'(x) = 2x + 2$, $f''(x) = 2$.

Avem că:
- $f$ este de clasă $C^2$
- $f'$ și $f''$ nu se anulează pe $[0.1, 2]$
- $f(0.1) f(2) = -0.79 \cdot 7 < 0$

Dacă luăm $x_0 = 1$ avem $f(x_0) f''(x_0) = 2 \cdot 2 > 0$, deci ipotezele teoremei de convergență sunt satisfăcute.

### c)

In [29]:
def newton_rhapson(f, df, x0, epsilon=1e-3):
    # Primul punct este cel primit ca parametru
    prev_x = x0
    # Aplicăm prima iterație
    x = x0 - f(x0) / df(x0)

    # Continuăm să calculăm până avem precizia cerută.
    last_rel_error = math.inf
    while abs(x - prev_x) / abs(prev_x) > epsilon:
        print(f"x = {x}, error = {last_rel_error}")
        x, prev_x = x - f(x) / df(x), x

        last_rel_error = abs((x - prev_x)) / abs(prev_x)

    return x

f = lambda x: x**2 + 2 * x - 1
df = lambda x: 2 * x + 2
x0 = 1
newton_rhapson(f, df, x0)

x = 0.5, error = inf
x = 0.4166666666666667, error = 0.16666666666666663
x = 0.41421568627450983, error = 0.00588235294117645


0.41421356237468987

## Exercițiul 3

In [41]:
A1 = np.array([
    [1, 0, -2],
    [2, -2, 0],
    [1, 2, 1],
], dtype=np.float64)
b1 = np.array([
    [-5],
    [-6],
    [5]
], dtype=np.float64)

A2 = np.array([
    [2, -2, 1],
    [1, 3, -2],
    [3, -1, -1]
], dtype=np.float64)
b2 = np.array([
    [-3],
    [1],
    [2]
], dtype=np.float64)

In [46]:
def compute_upper_triangular(A, b, partial_pivot=False, full_pivot=False):
    """Aduce un sistem la forma superior triunghiulară
    folosind Gauss cu/fără pivotare totală/parțială.
    """
    if partial_pivot and full_pivot:
        raise Exception("Se poate folosi doar un tip de pivotare")

    N = A.shape[0]

    # Formez matricea sistemului
    M = np.concatenate((A, b), axis=1)

    indices = np.arange(0, N)

    for k in range(N - 1):
        print(M)

        if partial_pivot:
            # Găsesc indicele elementului de valoare maximă
            index = np.argmax(M[k:, k])

            # Pivotez
            M[[k, index]] = M[[index, k]]
        elif full_pivot:
            submatrix = M[k:, k:N - 1]
            index = np.unravel_index(np.argmax(np.abs(submatrix)), submatrix.shape)

            # Obțin indicii în matricea mare
            index = (index[0] + k, index[1] + k)

            M[[k, index[0]]] = M[[index[0], k]]
            M[:, [k, index[1]]] = M[:, [index[1], k]]

            indices[[k, index[1]]] = indices[[index[1], k]]

        # Selectez coloana
        ratios = M[k + 1:, k]

        # Determin raportul pentru fiecare rând
        ratios = ratios / M[k, k]

        row = M[k, :]

        # Înmulțesc fiecare raport cu primul rând
        difference = np.outer(ratios, row)

        # Actualizez matricea
        M[k + 1:, :] -= difference

    return M, indices


def solve_upper_triangular(U, C, print_steps=False):
    """Rezolvă un sistem în formă superior triunghiulară,
    folosind substituția descendentă.
    """
    N = U.shape[0]

    x = np.zeros(N)

    # Merg de la ultima linie către prima,
    # și rezolv pe rând ecuațiile prin substituție
    for i in range(N - 1, -1, -1):
        coefs = U[i, i + 1:]
        values = x[i + 1:]

        x[i] = (C[i] - coefs @ values) / U[i, i]

        if print_steps:
            print("Pasul", N - i, ":",
                C[i], "-", coefs, "@", values, ")",
                "/", U[i, i])

    return x


def solve_system(A, b, pivot=None):
    "Rezolvă un sistem folosind metoda Gauss."

    determinant = np.linalg.det(A)

    if np.abs(determinant) < 1e-14:
        # Sistemul nu are soluție
        return None

    partial_pivot = False
    full_pivot = False

    if pivot == "full":
        full_pivot = True
    elif pivot == "partial":
        partial_pivot = True

    M, indices = compute_upper_triangular(A, b, partial_pivot=partial_pivot, full_pivot=full_pivot)

    N = A.shape[0]
    U = M[:,:N]
    C = M[:,N]

    x = solve_upper_triangular(U, C)
    x = x[indices]

    return x

print(solve_system(A1, b1, pivot='partial'))
print()
print(solve_system(A2, b2, pivot='full'))

[[ 1.  0. -2. -5.]
 [ 2. -2.  0. -6.]
 [ 1.  2.  1.  5.]]
[[ 2. -2.  0. -6.]
 [ 0.  1. -2. -2.]
 [ 0.  3.  1.  8.]]
[-1.  2.  2.]

[[ 2. -2.  1. -3.]
 [ 1.  3. -2.  1.]
 [ 3. -1. -1.  2.]]
[[ 3.          1.         -2.          1.        ]
 [ 0.          2.66666667 -0.33333333 -2.33333333]
 [ 0.          3.33333333 -1.66666667  2.33333333]]
[-1.4 -2.  -4.2]


## Exercițiul 4

In [52]:
A = np.array([
    [2, 3, 1],
    [4, 8, 4],
    [-4, 0, 10],
], dtype=np.float64)


b = np.array([
    [5],
    [18],
    [20],
], dtype=np.float64)

In [53]:

N = A.shape[0]
P = np.eye(N)
L = np.zeros((N, N))
U = np.copy(A)

partial_pivot = True

for k in range(N - 1):
    if partial_pivot:
        # Găsesc indicele elementului de magnitudine maximă
        index = k + np.argmax(np.abs(U[k:, k]))

        # Pivotez
        U[[k, index]] = U[[index, k]]
        L[[k, index]] = L[[index, k]]

        # Interschimb în permutare
        P[[k, index]] = P[[index, k]]

    # Selectez coloana pe care lucrez
    ratios = U[k + 1:, k]

    # Determin raportul pentru fiecare rând
    ratios = ratios / U[k, k]

    # Actualizez matricea inferior triunghiulară
    L[k + 1:, k] = ratios

    # Selectez rândul pe care vreau să-l actualizez
    row = U[k, :]

    # Înmulțesc fiecare raport cu primul rând
    difference = np.outer(ratios, row)

    # Actualizez matricea superior triunghiulară
    U[k + 1:, :] -= difference

L += np.eye(N)

print("L = ")
print(L)
print("U = ")
print(U)
print("L @ U = ")
print(L @ U)
print("P @ A = ")
print(P @ A)
print()


print("Rezolv pentru b = ", b.T)

# Permut numerele din vector
b = P @ b


y = np.zeros(N)

# Merg de la prima linie în jos,
# și rezolv pe rând ecuațiile prin substituție
for i in range(0, N):
    coefs = L[i, :i + 1]
    values = y[:i + 1]

    y[i] = (b[i] - coefs @ values) / L[i, i]

print("Obțin y = ", y)


x = np.zeros(N)

# Merg de la ultima linie în sus,
# și rezolv pe rând ecuațiile prin substituție
for i in range(N - 1, -1, -1):
    coefs = U[i, i + 1:]
    values = x[i + 1:]

    x[i] = (y[i] - coefs @ values) / U[i, i]

print("Obțin x = ", x)
print("Verificare: A @ x = ", A @ x)

L = 
[[ 1.     0.     0.   ]
 [-1.     1.     0.   ]
 [ 0.5   -0.125  1.   ]]
U = 
[[ 4.    8.    4.  ]
 [ 0.    8.   14.  ]
 [ 0.    0.    0.75]]
L @ U = 
[[ 4.  8.  4.]
 [-4.  0. 10.]
 [ 2.  3.  1.]]
P @ A = 
[[ 4.  8.  4.]
 [-4.  0. 10.]
 [ 2.  3.  1.]]

Rezolv pentru b =  [[ 5. 18. 20.]]
Obțin y =  [18.   38.    0.75]
Obțin x =  [-2.5  3.   1. ]
Verificare: A @ x =  [ 5. 18. 20.]


## Exercițiul 5

In [57]:
A = np.array([
    [4, 2, 4],
    [2, 2, 3],
    [4, 3, 14]
])

### a)

In [58]:
def simetrica(M):
    "Verifică dacă matricea `M` este simetrică."
    return np.all(M == M.T)

simetrica(A)

True

In [59]:
def pozitiv_semidefinita(M):
    "Verifică dacă matricea M este pozitiv-semidefinită."
    for i in range(M.shape[0]):
        minor = M[:i, :i]
        # Dacă cel puțin un minor principal nu are determinantul nenegativ,
        # nu este pozitiv-semidefinită.
        if np.linalg.det(minor) < 0:
            return False
    return True

pozitiv_semidefinita(A)

True

### b)

In [62]:
def descompunere_cholesky(M):
    N = M.shape[0]

    L = np.eye(N)

    for i in range(N):
        L_i = np.eye(N)

        pivot = M[i, i]
        L_i[i:, i] = M[i:, i] / np.sqrt(pivot)

        M_nou = np.eye(N)
        outer = np.outer(M[i + 1:, i], M[i, i + 1:])
        M_nou[i + 1:, i + 1:] = M[i + 1:, i + 1:] - outer / pivot

        L = L @ L_i
        M = M_nou

    return L

L = descompunere_cholesky(A)
print(L)

[[2. 0. 0.]
 [1. 1. 0.]
 [2. 1. 3.]]


### c)

Din descompunerea Cholesky am obținut $L$, și știm că $A = L L^T$.

Ecuația se rescrie

$$L L^T x = b$$

Deci putem rezolva mai întâi sistemul inferior triunghiular

$$L y = b$$

Și apoi cel superior triunghiular

$$L^T x = y$$

In [63]:
b = np.array([
    [10],
    [6],
    [11]
])

In [65]:
def substitutie_descendenta(U, b):
    N = b.shape[0]
    x = np.zeros(N)

    for i in range(N - 1, -1, -1):
        coefs = U[i, i + 1:]
        values = x[i + 1:]

        x[i] = (b[i] - coefs @ values) / U[i, i]

    return x

def substitutie_ascendenta(L, b):
    N = b.shape[0]
    x = np.zeros(N)

    for i in range(0, N):
        coefs = L[i, :i + 1]
        values = x[:i + 1]

        x[i] = (b[i] - coefs @ values) / L[i, i]

    return x

y = substitutie_ascendenta(L, b)
x = substitutie_descendenta(L.T, y)
print("x =",x)

x = [2. 1. 0.]
