# Tema 2

In [1]:
import numpy as np

## 1. Inversa unei matrici

Folosim metoda Gauss. 

In [2]:
def GPP(M):
    N = M.shape[0]
    M = M.copy()

    for k in range(N - 1):
        pivot = M[k, k]
        
        # Mă asigur că fiecare rând începe cu 1
        if pivot != 1:
            M[k] *= 1/pivot

        # Selectez coloana
        ratios = M[k + 1:, k]

        # Determin raportul pentru fiecare rând
        ratios = ratios / M[k, k]

        row = M[k, :]

        # Înmulțesc fiecare raport cu primul rând
        difference = np.outer(ratios, row)

        # Actualizez matricea
        M[k + 1:, :] -= difference

    return M

def inverse(A):
    N = A.shape[0]
    
    M = np.hstack((A, np.eye(3)))
    
    U = GPP(M)

    for i in range(1, N):
        for j in range(i):
            ratio = U[j, i] / U[i, i]
            U[j] -= ratio * U[i, :]

    return U[:, N:]

In [3]:
A = np.array([
    [1, 0, 5],
    [2, 1, 6],
    [3, 4, 0]
], dtype=np.float)

inv = inverse(A)

print(inv)

[[-24.  20.  -5.]
 [ 18. -15.   4.]
 [  5.  -4.   1.]]


## 2. Lema substituției

In [4]:
B = np.array([
    [1, 0, 0],
    [0, 2, 0],
    [0, 0, 1]
])
N = B.shape[0]

B_inv = inverse(B)

C = np.array([2, 1, 1], dtype=np.float)

k = 1

B_tilde = B.copy()
B_tilde[:, k] = C

In [5]:
y = B_inv @ C

eta = -y / y[k]
eta[k] = 1 / y[k]

E_k = np.eye(N)
E_k[:, k] = eta

B_tilde_inv = E_k @ B_inv

print("Inversul lui B_tilde:")
print(B_tilde_inv)

Inversul lui B_tilde:
[[ 1. -2.  0.]
 [ 0.  1.  0.]
 [ 0. -1.  1.]]
